const WHATSAPP_NUMBER="593992626500";
const CART_KEY="amigurumiland_cart";
const DB_KEY="amigurumiland_db";
const CHECKOUT_KEY="amigurumiland_checkout";
const products=[
{id:1,name:"Osito",cat:"Animales",price:8.9,slug:"osito-miel",stock:8,image:"https://i.pinimg.com/1200x/58/94/74/589474d5455ace4fa3c3fca76d6be156.jpg"},
{id:2,name:"Hatsune Miku",cat:"Personajes",price:15.9,slug:"hatsune-miku",stock:5,image:"assets/ChatGPT%20Image%202%20oct%202026%2C%2007_57_32%20p.m..png"},
{id:3,name:"Tulipán",cat:"Regalos",price:5.5,slug:"tulipan",stock:10,image:"https://i.pinimg.com/736x/8b/10/1b/8b101b438583fa269bb28b37d52bbed6.jpg"},
{id:4,name:"Rosa",cat:"Regalos",price:5,slug:"rosa",stock:5,image:"https://i.pinimg.com/736x/d7/fa/3c/d7fa3cfc0f1d68ce340167189c2cfda8.jpg"}];
const colors=[["Crema","#e7d3bb"],["Rosa","#e7aab4"],["Celeste","#a9c7df"],["Lavanda","#bdb2d8"],["Gris","#aeb2b5"],["Negro","#111"]];
const sizes=[["Pequeño (15 cm)",0],["Mediano (20 cm)",3],["Grande (30 cm)",6]];
let cart=loadCart(), statusTimer;

const money=n=>`$${Number(n).toFixed(2)}`;
const img=p=>p.image||`assets/products/${p.slug}-frente.svg`;
function showStatus(message){const el=document.getElementById("statusMessage");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(statusTimer);statusTimer=setTimeout(()=>el.classList.remove("show"),3500)}
function escapeHtml(v){const d=document.createElement("span");d.textContent=String(v);return d.innerHTML}
function toggleNav(){const h=document.querySelector(".nav");const b=document.querySelector(".menu-btn");const open=h.classList.toggle("menu-open");b.setAttribute("aria-expanded",open);b.setAttribute("aria-label",open?"Cerrar menú":"Abrir menú")}
function closeNav(){document.querySelector(".nav")?.classList.remove("menu-open")}
function updateCartCount(){const n=cart.reduce((s,x)=>s+x.qty,0);const el=document.getElementById("cartCount");if(el)el.textContent=n}
function loadCart(){try{const a=JSON.parse(localStorage.getItem(CART_KEY)||"[]");return Array.isArray(a)?a.filter(x=>products.some(p=>p.id===x.id)&&Number(x.qty)>0).map(x=>({...x,qty:Number(x.qty)})):[]}catch{return[]}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount()}
function totalCart(){return cart.reduce((sum,x)=>{const p=products.find(p=>p.id===x.id);return sum+(p.price+(Number(x.extra)||0))*x.qty},0)}
function customization(x){return x.color==="Original"?x.size:`${x.color} · ${x.size}`}
function renderProducts(){
 const box=document.getElementById("products");if(!box)return;
 const q=(document.getElementById("search")?.value||"").toLowerCase().trim(), c=document.getElementById("category")?.value||"";
 const result=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!c||p.cat===c));
 box.innerHTML=result.length?result.map(p=>`<article class="card"><img class="card-img" src="${img(p)}" alt="${p.name}" onerror="this.onerror=null;this.src='assets/amigurumis.png'"><div class="card-body"><div class="muted">${p.cat}</div><h3>${p.name}</h3><div class="price">${money(p.price)}</div><p class="muted">${p.stock} disponibles</p><a class="btn dark full" href="producto.html?id=${p.id}">Ver producto</a></div></article>`).join(""):'<p class="empty-results">No encontramos productos con esos filtros.</p>';
}
function getProduct(){return products.find(p=>String(p.id)===new URLSearchParams(location.search).get("id"))}
function openProductPage(){
 const p=getProduct(), box=document.getElementById("productDetail");if(!box)return;
 if(!p){box.innerHTML='<div class="notice">No encontramos ese producto.</div>';return}
 window.custom={color:p.slug==="hatsune-miku"?"Original":colors[0][0],size:sizes[0][0],extra:0,basePrice:p.price};
 box.innerHTML=`<div class="product"><div><img class="main-img" src="${img(p)}" alt="${p.name}" onerror="this.onerror=null;this.src='assets/amigurumis.png'"></div><div><div class="muted">${p.cat}</div><h1>${p.name}</h1><p>Elige la personalización antes de agregar el producto al carrito.</p>${p.slug!=="hatsune-miku"?`<b>Color</b><div class="option-row">${colors.map((c,i)=>`<button class="swatch ${i===0?"active":""}" type="button" aria-label="Elegir color ${c[0]}" aria-pressed="${i===0}" style="background:${c[1]}" onclick="chooseColor(${i},this)"></button>`).join("")}</div><p id="selectedColor" class="selection-label">Color seleccionado: ${colors[0][0]}</p>`:""}<b>Tamaño</b><div class="option-row">${sizes.map((s,i)=>`<button class="size ${i===0?"active":""}" type="button" aria-pressed="${i===0}" onclick="chooseSize(${i},this)">${s[0]}</button>`).join("")}</div><p id="selectedPrice" class="price">Precio: ${money(p.price)}</p><button class="btn dark full" onclick="addCustomized(${p.id})">Agregar al carrito</button><div class="help">¿Tienes dudas? <a href="${contactUrl(p.name)}" target="_blank" rel="noopener">Consultar por WhatsApp</a></div></div></div><div class="reviews-box"><h2>Reseñas</h2><div id="reviewsList">${renderReviews(p.id)}</div><div class="review-form"><label>Calificación<select id="reviewRating"><option value="5">5 ★★★★★</option><option value="4">4 ★★★★☆</option><option value="3">3 ★★★☆☆</option><option value="2">2 ★★☆☆☆</option><option value="1">1 ★☆☆☆☆</option></select></label><label>Tu reseña<textarea id="reviewText" rows="3" placeholder="Cuéntanos tu experiencia..."></textarea></label><p id="reviewFeedback" class="form-error"></p><button class="btn dark" onclick="submitReview(${p.id})">Enviar reseña</button></div></div>`;
}
function chooseColor(i,b){window.custom.color=colors[i][0];document.querySelectorAll(".swatch").forEach(x=>{x.classList.remove("active");x.setAttribute("aria-pressed","false")});b.classList.add("active");b.setAttribute("aria-pressed","true");document.getElementById("selectedColor").textContent=`Color seleccionado: ${window.custom.color}`}
function chooseSize(i,b){window.custom.size=sizes[i][0];window.custom.extra=sizes[i][1];document.querySelectorAll(".size").forEach(x=>{x.classList.remove("active");x.setAttribute("aria-pressed","false")});b.classList.add("active");b.setAttribute("aria-pressed","true");document.getElementById("selectedPrice").textContent=`Precio: ${money(window.custom.basePrice+window.custom.extra)}`}
function addCustomized(id){const p=products.find(x=>x.id===id),c=window.custom;const key=`${id}|${c.color}|${c.size}`,existing=cart.find(x=>x.key===key),qty=cart.filter(x=>x.id===id).reduce((s,x)=>s+x.qty,0);if(qty>=p.stock){showStatus(`Solo hay ${p.stock} unidades disponibles.`);return}if(existing)existing.qty++;else cart.push({key,id,qty:1,color:c.color,size:c.size,extra:c.extra});saveCart();showStatus(`${p.name} agregado al carrito.`);location.href="carrito.html"}
function renderCartPage(){
 const box=document.getElementById("cartItems");if(!box)return;
 if(!cart.length){box.innerHTML='<div class="empty-cart"><h2>Tu carrito está vacío</h2><p class="muted">Explora nuestros amigurumis y agrega tu favorito.</p><a class="btn dark" href="productos.html">Ver productos</a></div>';document.getElementById("subtotal").textContent="$0.00";document.getElementById("checkoutButton").classList.add("disabled");document.getElementById("checkoutButton").setAttribute("aria-disabled","true");return}
 box.innerHTML=cart.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<article class="cart-item"><img src="${img(p)}" alt="${p.name}" onerror="this.onerror=null;this.src='assets/amigurumis.png'"><div><h3>${p.name}</h3><p class="muted">${customization(x)}</p><div class="qty"><button onclick="changeQty(${i},-1)" aria-label="Restar una unidad de ${p.name}">−</button><span aria-label="Cantidad">${x.qty}</span><button onclick="changeQty(${i},1)" aria-label="Agregar una unidad de ${p.name}">+</button></div></div><b>${money((p.price+x.extra)*x.qty)}</b></article>`}).join("");
 document.getElementById("subtotal").textContent=money(totalCart());const b=document.getElementById("checkoutButton");b.classList.remove("disabled");b.removeAttribute("aria-disabled")
}
function changeQty(i,d){const item=cart[i];if(!item)return;const p=products.find(x=>x.id===item.id);const qty=cart.filter(x=>x.id===item.id).reduce((s,x)=>s+x.qty,0);if(d>0&&qty>=p.stock){showStatus(`Solo hay ${p.stock} unidades disponibles.`);return}if(d<0&&item.qty===1){const ok=window.confirm(`El producto "${p.name}" está en 1 unidad. ¿Estás seguro de que deseas quitarlo del carrito?`);if(!ok)return}item.qty+=d;if(item.qty<=0)cart.splice(i,1);saveCart();renderCartPage()}
function checkoutSummary(target){const box=document.getElementById(target);if(!box)return;box.innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="summary-line"><span>${p.name}<small>${customization(x)} × ${x.qty}</small></span><b>${money((p.price+x.extra)*x.qty)}</b></div>`}).join("")+`<hr><div class="summary-total"><span>Total</span><b>${money(totalCart())}</b></div>`:'<p class="muted">Tu carrito está vacío.</p>'}
function getCheckout(){try{return JSON.parse(sessionStorage.getItem(CHECKOUT_KEY)||"null")}catch{return null}}
function saveCheckoutData(){if(!cart.length){location.href="carrito.html";return}const name=document.getElementById("name"),email=document.getElementById("email"),err=document.getElementById("checkoutDataError");if(!name.value.trim()){err.textContent="Escribe tu nombre completo.";name.focus();return}if(!email.checkValidity()){err.textContent="Escribe un correo válido.";email.focus();return}const data={name:name.value.trim(),email:email.value.trim(),pickup:document.querySelector("[name=pickup]:checked").value};sessionStorage.setItem(CHECKOUT_KEY,JSON.stringify(data));location.href="checkout-pago.html"}
function isValidCardNumber(v){const d=v.replace(/\D/g,"");if(!/^\d{16}$/.test(d))return false;let sum=0,double=false;for(let i=d.length-1;i>=0;i--){let n=+d[i];if(double)n=n*2>9?n*2-9:n*2;sum+=n;double=!double}return sum%10===0}
function updatePaymentFields(){const m=document.querySelector("[name=payment]:checked")?.value;document.getElementById("cardPaymentFields")?.toggleAttribute("hidden",m!=="Tarjeta");document.getElementById("transferPaymentFields")?.toggleAttribute("hidden",m!=="Transferencia bancaria");document.getElementById("paypalPaymentFields")?.toggleAttribute("hidden",m!=="PayPal")}
function validatePayment(){const m=document.querySelector("[name=payment]:checked").value,err=document.getElementById("paymentError");if(m==="Tarjeta"){const name=document.getElementById("cardholderName"),num=document.getElementById("cardNumber"),exp=document.getElementById("cardExpiry"),cvv=document.getElementById("cardCvv");if(!name.value.trim()){err.textContent="Ingresa un nombre de titular de prueba.";name.focus();return null}if(!isValidCardNumber(num.value)){err.textContent="Usa un número de tarjeta de prueba válido de 16 dígitos. Ejemplo: 4242 4242 4242 4242.";num.focus();return null}if(!/^(0[1-9]|1[0-2])\/\d{2}$/.test(exp.value.trim())){err.textContent="Usa el formato MM/AA.";exp.focus();return null}if(!/^\d{3,4}$/.test(cvv.value.trim())){err.textContent="El CVV de prueba debe tener 3 o 4 dígitos.";cvv.focus();return null}return{status:"approved"}}if(m==="Transferencia bancaria"){const r=document.getElementById("transferReference");if(!/^[A-Za-z0-9-]{6,20}$/.test(r.value.trim())){err.textContent="La referencia debe tener entre 6 y 20 letras, números o guiones.";r.focus();return null}return{status:"pending_verification",reference:r.value.trim()}}const e=document.getElementById("paypalEmail");if(!e.checkValidity()){err.textContent="Ingresa un correo válido de prueba.";e.focus();return null}return{status:"approved"}}
function loadDB(){try{return JSON.parse(localStorage.getItem(DB_KEY)||'{"USUARIO":[],"DIRECCION":[],"PEDIDO":[],"DETALLE_PEDIDO":[],"PAGO":[],"ENVIO":[],"RESENA":[]}')}catch{return null}}
function saveDB(db){try{localStorage.setItem(DB_KEY,JSON.stringify(db));return true}catch{return false}}
function processPayment(){const data=getCheckout(),err=document.getElementById("paymentError");if(!data){location.href="checkout-datos.html";return}const payment=validatePayment();if(!payment)return;const now=new Date(),orderId="AM-"+Date.now().toString().slice(-6),db=loadDB();if(!db){err.textContent="No fue posible guardar la simulación.";return}
 const userId="USR-"+Date.now().toString().slice(-6),payId="PAY-"+Date.now().toString().slice(-6),detailIds=cart.map((_,i)=>`DET-${Date.now().toString().slice(-6)}-${i+1}`);
 db.USUARIO.push({id:userId,nombre:data.name,email:data.email});db.DIRECCION.push({id:"DIR-"+orderId,usuario_id:userId,punto_retiro:data.pickup});
 db.PEDIDO.push({id:orderId,usuario_id:userId,fecha:now.toISOString(),estado:"Pendiente",total:totalCart(),punto_retiro:data.pickup,metodo_pago:document.querySelector("[name=payment]:checked").value});
 cart.forEach((x,i)=>{const p=products.find(p=>p.id===x.id);db.DETALLE_PEDIDO.push({id:detailIds[i],pedido_id:orderId,producto_id:p.id,cantidad:x.qty,color:x.color,tamano:x.size,precio_unitario:p.price+(x.extra||0)})});
 db.PAGO.push({id:payId,pedido_id:orderId,metodo:document.querySelector("[name=payment]:checked").value,estado:payment.status,referencia:payment.reference||"SIMULACION",fecha:now.toISOString()});
 db.ENVIO.push({id:"ENV-"+orderId,pedido_id:orderId,punto_retiro:data.pickup,estado:"Pendiente",fecha_disponible:new Date(now.getTime()+7*86400000).toISOString()});
 if(!saveDB(db)){err.textContent="No se pudo guardar la transacción simulada.";return}
 sessionStorage.setItem("LAST_ORDER",JSON.stringify({id:orderId,paymentStatus:payment.status,paymentMethod:document.querySelector("[name=payment]:checked").value,total:totalCart()}));
 cart=[];saveCart();sessionStorage.removeItem(CHECKOUT_KEY);location.href="confirmacion.html"}
function initPayment(){if(!getCheckout())return location.href="checkout-datos.html";checkoutSummary("paymentSummary")}
function initData(){if(!cart.length)return location.href="carrito.html";checkoutSummary("checkoutSummary")}
function initConfirmation(){const o=JSON.parse(sessionStorage.getItem("LAST_ORDER")||"null");if(!o)return;document.getElementById("confirmationText").textContent=`Tu pedido ${o.id} fue registrado correctamente. No se realizó ningún cobro real.`;document.getElementById("confirmationCard").innerHTML=`<p><b>Código del pedido</b><br>${escapeHtml(o.id)}</p><p><b>Método</b><br>${escapeHtml(o.paymentMethod)}</p><p><b>Estado del pago</b><br>${o.paymentStatus==="approved"?"Aprobado (simulación)":"Pendiente de verificación"}</p><p><b>Total simulado</b><br>${money(o.total)}</p>`}
function lookupOrder(){const code=document.getElementById("orderCode").value.trim().toUpperCase(),email=document.getElementById("orderEmail").value.trim().toLowerCase(),db=loadDB(),result=document.getElementById("orderLookupResult");if(!db)return;const user=db.USUARIO.find(u=>u.email.toLowerCase()===email),order=user&&db.PEDIDO.find(p=>p.id===code&&p.usuario_id===user.id);if(!order){result.innerHTML='<p class="order-empty">No encontramos un pedido con esos datos. Verifica el código y el correo.</p>';return}const details=db.DETALLE_PEDIDO.filter(d=>d.pedido_id===order.id),pay=db.PAGO.find(p=>p.pedido_id===order.id),env=db.ENVIO.find(e=>e.pedido_id===order.id);result.innerHTML=`<article class="order-card"><div class="order-card-header"><div><b>Pedido ${escapeHtml(order.id)}</b><time>${new Date(order.fecha).toLocaleString("es-EC",{dateStyle:"medium",timeStyle:"short"})}</time></div><span class="order-status is-pending">${escapeHtml(order.estado)}</span></div><ul class="order-items">${details.map(d=>{const p=products.find(p=>p.id===d.producto_id);return `<li>${escapeHtml(p?.name||"Producto")} · ${escapeHtml(d.tamano)} × ${d.cantidad}</li>`}).join("")}</ul><div class="order-card-footer"><span>Retiro: ${escapeHtml(order.punto_retiro)}</span><b>Total: ${money(order.total)}</b></div><p class="muted">Pago: ${pay?.estado==="approved"?"Aprobado (simulación)":"Transferencia por verificar"}</p><p class="muted">Disponible para recoger desde: ${new Date(env.fecha_disponible).toLocaleDateString("es-EC",{dateStyle:"long"})}</p></article>`}
function getReviews(id){try{return JSON.parse(localStorage.getItem(`amigurumiland_reviews_${id}`)||"[]")}catch{return[]}}
function renderReviews(id){const r=getReviews(id);return r.length?r.map(x=>`<div class="review-item"><b>${"★".repeat(x.rating)}${"☆".repeat(5-x.rating)}</b><p>${escapeHtml(x.comment)}</p><span class="muted">${new Date(x.date).toLocaleDateString("es-EC")}</span></div>`).join(""):'<p class="muted">Aún no hay reseñas para este producto.</p>'}
function submitReview(id){const t=document.getElementById("reviewText"),f=document.getElementById("reviewFeedback");if(!t.value.trim()){f.textContent="Escribe una reseña antes de enviarla.";t.focus();return}const r=getReviews(id);r.unshift({rating:+document.getElementById("reviewRating").value,comment:t.value.trim(),date:new Date().toISOString()});localStorage.setItem(`amigurumiland_reviews_${id}`,JSON.stringify(r));t.value="";document.getElementById("reviewsList").innerHTML=renderReviews(id);f.textContent="Reseña guardada en este navegador."}
function contactUrl(name){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`Hola, quiero consultar sobre ${name} en Amigurumiland.`)}`}
function submitQuote(){const n=document.getElementById("quoteName"),e=document.getElementById("quoteEmail"),f=document.getElementById("quoteFeedback");if(!n.value.trim()||!e.checkValidity()){f.textContent="Completa tu nombre y un correo válido.";return}f.textContent="Solicitud de cotización guardada como demostración del prototipo."}
document.addEventListener("DOMContentLoaded",()=>{
 updateCartCount();
 const wa=document.getElementById("waLink");if(wa)wa.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("Hola, necesito ayuda con mi pedido o personalización en Amigurumiland.")}`;
 const waf=document.getElementById("waLinkFooter");if(waf)waf.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("Hola, necesito ayuda con mi pedido o personalización en Amigurumiland.")}`;
 renderProducts();renderCartPage();openProductPage();
 if(document.getElementById("checkoutSummary"))initData();
 if(document.getElementById("paymentSummary"))initPayment();
 if(document.getElementById("confirmationCard"))initConfirmation();
 document.querySelectorAll("[name=payment]").forEach(x=>x.addEventListener("change",updatePaymentFields));updatePaymentFields();
});
